targetInstance: ${TEST_URL:http://localhost:8686}

ccdGatewayUrl: ${CCD_GW_URL:http://localhost:3453}

idam:
  redirectUrl: ${IA_IDAM_REDIRECT_URI:http://localhost:3002/oauth2/callback}
  scope: "openid profile roles"

feign:
  hystrix:
    enabled: false

spring:
  cache:
    cache-names: userInfoCache, accessTokenCache, legalRepATokenCache, caseOfficerTokenCache, adminOfficerTokenCache, homeOfficeApcTokenCache, homeOfficeBailTokenCache, homeOfficeLartTokenCache, homeOfficePouTokenCache, homeOfficeGenericTokenCache, legalRepShareCaseATokenCache, legalRepOrgSuccessTokenCache, legalRepOrgDeletedTokenCache, judgeTokenCache, citizenTokenCache
    caffeine:
      spec: expireAfterWrite=3600s
