apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Bail Case API App
name: ia-bail-case-api
home: https://github.com/hmcts/ia-bail-case-api
version: 0.0.5
maintainers:
  - name: Immigration & Asylum Team
    email: ImmigrationandAsylum@HMCTS.NET
dependencies:
  - name: java
    version: 3.7.2
    repository: '@hmctspublic'
