java:
  applicationPort: 4550
  image: 'hmctspublic.azurecr.io/ia/ia-bail-case-api:latest'
  ingressHost: ia-bail-case-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: ia
#  Uncomment once the vault containing the app insights key has been set up
#  keyVaults:
#    rpe:
#      secrets:
#        - name: AppInsightsInstrumentationKey
#          alias: azure.application-insights.instrumentation-key
  environment:
    IA_IDAM_REDIRECT_URI: "https://ia-case-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2/callback"
    IDAM_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    OPEN_ID_IDAM_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
  keyVaults:
    ia:
      secrets:
        - idam-client-id
        - idam-secret


